#3 Menu
SamanthaDi/Castle-in-the-sky pull request #4
Opened 2021-06-01 05:54 UTC by SamanthaDi

Los botones funcionan, dirigen a un nuevo mundo pero estos no están terminados aun.

2021-06-01 13:22 UTC, iuresti requested changes

2021-06-01 13:22 UTC, iuresti commented on Buttons.java
> +    private static int TRANS = 255;
No abreviaturas

2021-06-01 13:22 UTC, iuresti commented on Buttons.java
> +public class Buttons extends Actor
"Button" en lugar de "Buttons" .. las clases representan una entidad

2021-06-01 13:22 UTC, iuresti commented on Exit.java
> +public class Exit extends Buttons
ExitButton en lugar de Exit

2021-06-01 13:22 UTC, iuresti commented on Exit.java
> +        checkMouse();
Usa template method pattern

2021-06-01 13:22 UTC, iuresti commented on HowToPlay.java
> +public class HowToPlay extends Buttons
HowToPlayButton en lugar de HowToPlay

2021-06-01 13:22 UTC, iuresti commented on HowToPlay.java
> +        checkMouse();
template method

2021-06-01 13:22 UTC, iuresti commented on Main_menu.java
> +public class Main_menu extends World
No snake case, Usamos UpperCammelCase para nombrar clases (MainMenu en lugar de Main_menu)

2021-06-01 13:22 UTC, iuresti commented on Play.java
> +public class Play extends Buttons
PlayButton en lugar de Play

2021-06-01 13:22 UTC, iuresti commented on Play.java
> +    public GreenfootSound soundtrack = new GreenfootSound("Main_menu.mp3");
atributos deben ser privados

2021-06-01 13:22 UTC, iuresti commented on Play.java
> +    boolean firstTurn = true;
Necesitas que sea "package-private"? .. si no, hay que añadir modificador de acceso

2021-06-01 13:22 UTC, iuresti commented on Scores.java
> +public class Scores extends Buttons
ScoreButton en lugar de Scores

2021-06-02 07:02 UTC, SamanthaDi commented
Se editaron las partes explicadas en clase

2021-06-03 13:55 UTC, iuresti approved these changes

2021-06-03 14:03 UTC, merged